version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret

# Initialize the db using a init.sql on container startup
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql